//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostInfo) DeepCopyInto(out *HostInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostInfo.
func (in *HostInfo) DeepCopy() *HostInfo {
	if in == nil {
		return nil
	}
	out := new(HostInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceDesc) DeepCopyInto(out *InstanceDesc) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.RuntimeClassName != nil {
		in, out := &in.RuntimeClassName, &out.RuntimeClassName
		*out = new(string)
		**out = **in
	}
	if in.PriorityClassName != nil {
		in, out := &in.PriorityClassName, &out.PriorityClassName
		*out = new(string)
		**out = **in
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	out.Size = in.Size.DeepCopy()
	out.LogSize = in.LogSize.DeepCopy()
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceDesc.
func (in *InstanceDesc) DeepCopy() *InstanceDesc {
	if in == nil {
		return nil
	}
	out := new(InstanceDesc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBCluster) DeepCopyInto(out *KDBCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBCluster.
func (in *KDBCluster) DeepCopy() *KDBCluster {
	if in == nil {
		return nil
	}
	out := new(KDBCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBClusterList) DeepCopyInto(out *KDBClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDBCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBClusterList.
func (in *KDBClusterList) DeepCopy() *KDBClusterList {
	if in == nil {
		return nil
	}
	out := new(KDBClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBClusterSpec) DeepCopyInto(out *KDBClusterSpec) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]InstanceDesc, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Leader = in.Leader
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(MySQLSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(KDBProxySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PostgreSQL != nil {
		in, out := &in.PostgreSQL, &out.PostgreSQL
		*out = new(PostgreSQLSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(KDBProxySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBClusterSpec.
func (in *KDBClusterSpec) DeepCopy() *KDBClusterSpec {
	if in == nil {
		return nil
	}
	out := new(KDBClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBClusterStatus) DeepCopyInto(out *KDBClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(KDBProxyStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBClusterStatus.
func (in *KDBClusterStatus) DeepCopy() *KDBClusterStatus {
	if in == nil {
		return nil
	}
	out := new(KDBClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBInstance) DeepCopyInto(out *KDBInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBInstance.
func (in *KDBInstance) DeepCopy() *KDBInstance {
	if in == nil {
		return nil
	}
	out := new(KDBInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBInstanceList) DeepCopyInto(out *KDBInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDBInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBInstanceList.
func (in *KDBInstanceList) DeepCopy() *KDBInstanceList {
	if in == nil {
		return nil
	}
	out := new(KDBInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBInstanceSpec) DeepCopyInto(out *KDBInstanceSpec) {
	*out = *in
	in.InstanceSet.DeepCopyInto(&out.InstanceSet)
	out.Leader = in.Leader
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(MySQLSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PostgreSQL != nil {
		in, out := &in.PostgreSQL, &out.PostgreSQL
		*out = new(PostgreSQLSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Shutdown != nil {
		in, out := &in.Shutdown, &out.Shutdown
		*out = new(bool)
		**out = **in
	}
	if in.SupplementalGroups != nil {
		in, out := &in.SupplementalGroups, &out.SupplementalGroups
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBInstanceSpec.
func (in *KDBInstanceSpec) DeepCopy() *KDBInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(KDBInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBInstanceStatus) DeepCopyInto(out *KDBInstanceStatus) {
	*out = *in
	in.InstanceSet.DeepCopyInto(&out.InstanceSet)
	if in.PostgreSQL != nil {
		in, out := &in.PostgreSQL, &out.PostgreSQL
		*out = new(PostgreSQLStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(KDBProxyStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBInstanceStatus.
func (in *KDBInstanceStatus) DeepCopy() *KDBInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(KDBInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBLogSystem) DeepCopyInto(out *KDBLogSystem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBLogSystem.
func (in *KDBLogSystem) DeepCopy() *KDBLogSystem {
	if in == nil {
		return nil
	}
	out := new(KDBLogSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBLogSystem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBLogSystemList) DeepCopyInto(out *KDBLogSystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDBLogSystem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBLogSystemList.
func (in *KDBLogSystemList) DeepCopy() *KDBLogSystemList {
	if in == nil {
		return nil
	}
	out := new(KDBLogSystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBLogSystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBLogSystemSpec) DeepCopyInto(out *KDBLogSystemSpec) {
	*out = *in
	out.Endpoints = in.Endpoints
	if in.CredentialSecretRef != nil {
		in, out := &in.CredentialSecretRef, &out.CredentialSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	in.Collector.DeepCopyInto(&out.Collector)
	in.Gateway.DeepCopyInto(&out.Gateway)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBLogSystemSpec.
func (in *KDBLogSystemSpec) DeepCopy() *KDBLogSystemSpec {
	if in == nil {
		return nil
	}
	out := new(KDBLogSystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBLogSystemStatus) DeepCopyInto(out *KDBLogSystemStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBLogSystemStatus.
func (in *KDBLogSystemStatus) DeepCopy() *KDBLogSystemStatus {
	if in == nil {
		return nil
	}
	out := new(KDBLogSystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBMonitoringStack) DeepCopyInto(out *KDBMonitoringStack) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBMonitoringStack.
func (in *KDBMonitoringStack) DeepCopy() *KDBMonitoringStack {
	if in == nil {
		return nil
	}
	out := new(KDBMonitoringStack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBMonitoringStack) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBMonitoringStackList) DeepCopyInto(out *KDBMonitoringStackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDBMonitoringStack, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBMonitoringStackList.
func (in *KDBMonitoringStackList) DeepCopy() *KDBMonitoringStackList {
	if in == nil {
		return nil
	}
	out := new(KDBMonitoringStackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBMonitoringStackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBMonitoringStackSpec) DeepCopyInto(out *KDBMonitoringStackSpec) {
	*out = *in
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	in.Alertmanager.DeepCopyInto(&out.Alertmanager)
	in.Grafana.DeepCopyInto(&out.Grafana)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBMonitoringStackSpec.
func (in *KDBMonitoringStackSpec) DeepCopy() *KDBMonitoringStackSpec {
	if in == nil {
		return nil
	}
	out := new(KDBMonitoringStackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBMonitoringStackStatus) DeepCopyInto(out *KDBMonitoringStackStatus) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]MonitoringStackComponentStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBMonitoringStackStatus.
func (in *KDBMonitoringStackStatus) DeepCopy() *KDBMonitoringStackStatus {
	if in == nil {
		return nil
	}
	out := new(KDBMonitoringStackStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyBackendPolicySpec) DeepCopyInto(out *KDBProxyBackendPolicySpec) {
	*out = *in
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(KDBProxyHealthCheckSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyBackendPolicySpec.
func (in *KDBProxyBackendPolicySpec) DeepCopy() *KDBProxyBackendPolicySpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyBackendPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyBackendStatus) DeepCopyInto(out *KDBProxyBackendStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyBackendStatus.
func (in *KDBProxyBackendStatus) DeepCopy() *KDBProxyBackendStatus {
	if in == nil {
		return nil
	}
	out := new(KDBProxyBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyConfigMapRef) DeepCopyInto(out *KDBProxyConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyConfigMapRef.
func (in *KDBProxyConfigMapRef) DeepCopy() *KDBProxyConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(KDBProxyConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyConfigSpec) DeepCopyInto(out *KDBProxyConfigSpec) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(KDBProxyConfigMapRef)
		**out = **in
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(KDBProxyInlineConfigSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyConfigSpec.
func (in *KDBProxyConfigSpec) DeepCopy() *KDBProxyConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyHealthCheckSpec) DeepCopyInto(out *KDBProxyHealthCheckSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyHealthCheckSpec.
func (in *KDBProxyHealthCheckSpec) DeepCopy() *KDBProxyHealthCheckSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyHealthCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyHostgroupsStatus) DeepCopyInto(out *KDBProxyHostgroupsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyHostgroupsStatus.
func (in *KDBProxyHostgroupsStatus) DeepCopy() *KDBProxyHostgroupsStatus {
	if in == nil {
		return nil
	}
	out := new(KDBProxyHostgroupsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyInlineConfigSpec) DeepCopyInto(out *KDBProxyInlineConfigSpec) {
	*out = *in
	if in.Traffic != nil {
		in, out := &in.Traffic, &out.Traffic
		*out = new(KDBProxyTrafficPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = new(KDBProxyBackendPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]KDBProxyUserSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyInlineConfigSpec.
func (in *KDBProxyInlineConfigSpec) DeepCopy() *KDBProxyInlineConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyInlineConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyLoadBalanceSpec) DeepCopyInto(out *KDBProxyLoadBalanceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyLoadBalanceSpec.
func (in *KDBProxyLoadBalanceSpec) DeepCopy() *KDBProxyLoadBalanceSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyLoadBalanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyReadWriteSplitSpec) DeepCopyInto(out *KDBProxyReadWriteSplitSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyReadWriteSplitSpec.
func (in *KDBProxyReadWriteSplitSpec) DeepCopy() *KDBProxyReadWriteSplitSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyReadWriteSplitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyResourceSpec) DeepCopyInto(out *KDBProxyResourceSpec) {
	*out = *in
	in.ProxySQL.DeepCopyInto(&out.ProxySQL)
	in.Mgr.DeepCopyInto(&out.Mgr)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyResourceSpec.
func (in *KDBProxyResourceSpec) DeepCopy() *KDBProxyResourceSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyServiceSpec) DeepCopyInto(out *KDBProxyServiceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyServiceSpec.
func (in *KDBProxyServiceSpec) DeepCopy() *KDBProxyServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxySpec) DeepCopyInto(out *KDBProxySpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(KDBProxyConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(KDBProxyServiceSpec)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(KDBProxyResourceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxySpec.
func (in *KDBProxySpec) DeepCopy() *KDBProxySpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyStatus) DeepCopyInto(out *KDBProxyStatus) {
	*out = *in
	if in.Hostgroups != nil {
		in, out := &in.Hostgroups, &out.Hostgroups
		*out = new(KDBProxyHostgroupsStatus)
		**out = **in
	}
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]KDBProxyBackendStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyStatus.
func (in *KDBProxyStatus) DeepCopy() *KDBProxyStatus {
	if in == nil {
		return nil
	}
	out := new(KDBProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyTrafficPolicySpec) DeepCopyInto(out *KDBProxyTrafficPolicySpec) {
	*out = *in
	if in.ReadWriteSplit != nil {
		in, out := &in.ReadWriteSplit, &out.ReadWriteSplit
		*out = new(KDBProxyReadWriteSplitSpec)
		**out = **in
	}
	if in.LoadBalance != nil {
		in, out := &in.LoadBalance, &out.LoadBalance
		*out = new(KDBProxyLoadBalanceSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyTrafficPolicySpec.
func (in *KDBProxyTrafficPolicySpec) DeepCopy() *KDBProxyTrafficPolicySpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyTrafficPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyUserSpec) DeepCopyInto(out *KDBProxyUserSpec) {
	*out = *in
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyUserSpec.
func (in *KDBProxyUserSpec) DeepCopy() *KDBProxyUserSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogSystemCollectorSpec) DeepCopyInto(out *LogSystemCollectorSpec) {
	*out = *in
	if in.ExtraLogDirs != nil {
		in, out := &in.ExtraLogDirs, &out.ExtraLogDirs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigPatch != nil {
		in, out := &in.ConfigPatch, &out.ConfigPatch
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogSystemCollectorSpec.
func (in *LogSystemCollectorSpec) DeepCopy() *LogSystemCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(LogSystemCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogSystemEndpointSpec) DeepCopyInto(out *LogSystemEndpointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogSystemEndpointSpec.
func (in *LogSystemEndpointSpec) DeepCopy() *LogSystemEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(LogSystemEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogSystemGatewaySpec) DeepCopyInto(out *LogSystemGatewaySpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogSystemGatewaySpec.
func (in *LogSystemGatewaySpec) DeepCopy() *LogSystemGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(LogSystemGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringStackAlertmanagerSpec) DeepCopyInto(out *MonitoringStackAlertmanagerSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringStackAlertmanagerSpec.
func (in *MonitoringStackAlertmanagerSpec) DeepCopy() *MonitoringStackAlertmanagerSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringStackAlertmanagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringStackComponentStatus) DeepCopyInto(out *MonitoringStackComponentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringStackComponentStatus.
func (in *MonitoringStackComponentStatus) DeepCopy() *MonitoringStackComponentStatus {
	if in == nil {
		return nil
	}
	out := new(MonitoringStackComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringStackGrafanaSpec) DeepCopyInto(out *MonitoringStackGrafanaSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringStackGrafanaSpec.
func (in *MonitoringStackGrafanaSpec) DeepCopy() *MonitoringStackGrafanaSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringStackGrafanaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringStackPrometheusSpec) DeepCopyInto(out *MonitoringStackPrometheusSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringStackPrometheusSpec.
func (in *MonitoringStackPrometheusSpec) DeepCopy() *MonitoringStackPrometheusSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringStackPrometheusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLExporterSpec) DeepCopyInto(out *MySQLExporterSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLExporterSpec.
func (in *MySQLExporterSpec) DeepCopy() *MySQLExporterSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLMGRSpec) DeepCopyInto(out *MySQLMGRSpec) {
	*out = *in
	if in.BootstrapOrdinal != nil {
		in, out := &in.BootstrapOrdinal, &out.BootstrapOrdinal
		*out = new(int32)
		**out = **in
	}
	if in.GroupPort != nil {
		in, out := &in.GroupPort, &out.GroupPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLMGRSpec.
func (in *MySQLMGRSpec) DeepCopy() *MySQLMGRSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLMGRSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLSpec) DeepCopyInto(out *MySQLSpec) {
	*out = *in
	if in.MGR != nil {
		in, out := &in.MGR, &out.MGR
		*out = new(MySQLMGRSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Exporter != nil {
		in, out := &in.Exporter, &out.Exporter
		*out = new(MySQLExporterSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLSpec.
func (in *MySQLSpec) DeepCopy() *MySQLSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLBackupSpec) DeepCopyInto(out *PostgreSQLBackupSpec) {
	*out = *in
	if in.PGBackRest != nil {
		in, out := &in.PGBackRest, &out.PGBackRest
		*out = new(PostgreSQLPGBackRestSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLBackupSpec.
func (in *PostgreSQLBackupSpec) DeepCopy() *PostgreSQLBackupSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLExporterSpec) DeepCopyInto(out *PostgreSQLExporterSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLExporterSpec.
func (in *PostgreSQLExporterSpec) DeepCopy() *PostgreSQLExporterSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLPGBackRestSpec) DeepCopyInto(out *PostgreSQLPGBackRestSpec) {
	*out = *in
	if in.RepoSecretRef != nil {
		in, out := &in.RepoSecretRef, &out.RepoSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.RetentionFull != nil {
		in, out := &in.RetentionFull, &out.RetentionFull
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLPGBackRestSpec.
func (in *PostgreSQLPGBackRestSpec) DeepCopy() *PostgreSQLPGBackRestSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLPGBackRestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLPGBackRestStatus) DeepCopyInto(out *PostgreSQLPGBackRestStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLPGBackRestStatus.
func (in *PostgreSQLPGBackRestStatus) DeepCopy() *PostgreSQLPGBackRestStatus {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLPGBackRestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLPatroniSpec) DeepCopyInto(out *PostgreSQLPatroniSpec) {
	*out = *in
	if in.LeaderLeaseDurationSeconds != nil {
		in, out := &in.LeaderLeaseDurationSeconds, &out.LeaderLeaseDurationSeconds
		*out = new(int32)
		**out = **in
	}
	if in.SyncPeriodSeconds != nil {
		in, out := &in.SyncPeriodSeconds, &out.SyncPeriodSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLPatroniSpec.
func (in *PostgreSQLPatroniSpec) DeepCopy() *PostgreSQLPatroniSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLPatroniSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLSpec) DeepCopyInto(out *PostgreSQLSpec) {
	*out = *in
	if in.Patroni != nil {
		in, out := &in.Patroni, &out.Patroni
		*out = new(PostgreSQLPatroniSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Backups != nil {
		in, out := &in.Backups, &out.Backups
		*out = new(PostgreSQLBackupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialSecretRef != nil {
		in, out := &in.CredentialSecretRef, &out.CredentialSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Exporter != nil {
		in, out := &in.Exporter, &out.Exporter
		*out = new(PostgreSQLExporterSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HBA != nil {
		in, out := &in.HBA, &out.HBA
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLSpec.
func (in *PostgreSQLSpec) DeepCopy() *PostgreSQLSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLStatus) DeepCopyInto(out *PostgreSQLStatus) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]HostInfo, len(*in))
		copy(*out, *in)
	}
	if in.PGBackRest != nil {
		in, out := &in.PGBackRest, &out.PGBackRest
		*out = new(PostgreSQLPGBackRestStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLStatus.
func (in *PostgreSQLStatus) DeepCopy() *PostgreSQLStatus {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLStatus)
	in.DeepCopyInto(out)
	return out
}
