//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/sqc157400661/kdb/apis/shared"
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseBackupSpec) DeepCopyInto(out *ClickHouseBackupSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ObjectStorageRef != nil {
		in, out := &in.ObjectStorageRef, &out.ObjectStorageRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseBackupSpec.
func (in *ClickHouseBackupSpec) DeepCopy() *ClickHouseBackupSpec {
	if in == nil {
		return nil
	}
	out := new(ClickHouseBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseComputeGroupLifecycleSpec) DeepCopyInto(out *ClickHouseComputeGroupLifecycleSpec) {
	*out = *in
	if in.AutoSuspendEnabled != nil {
		in, out := &in.AutoSuspendEnabled, &out.AutoSuspendEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AutoSuspendAfter != nil {
		in, out := &in.AutoSuspendAfter, &out.AutoSuspendAfter
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.WarmReplicasPerShard != nil {
		in, out := &in.WarmReplicasPerShard, &out.WarmReplicasPerShard
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseComputeGroupLifecycleSpec.
func (in *ClickHouseComputeGroupLifecycleSpec) DeepCopy() *ClickHouseComputeGroupLifecycleSpec {
	if in == nil {
		return nil
	}
	out := new(ClickHouseComputeGroupLifecycleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseComputeGroupSpec) DeepCopyInto(out *ClickHouseComputeGroupSpec) {
	*out = *in
	in.Instance.DeepCopyInto(&out.Instance)
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(ClickHouseComputeGroupLifecycleSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseComputeGroupSpec.
func (in *ClickHouseComputeGroupSpec) DeepCopy() *ClickHouseComputeGroupSpec {
	if in == nil {
		return nil
	}
	out := new(ClickHouseComputeGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseComputeGroupStatus) DeepCopyInto(out *ClickHouseComputeGroupStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseComputeGroupStatus.
func (in *ClickHouseComputeGroupStatus) DeepCopy() *ClickHouseComputeGroupStatus {
	if in == nil {
		return nil
	}
	out := new(ClickHouseComputeGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseGatewaySpec) DeepCopyInto(out *ClickHouseGatewaySpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(shared.ServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BindingSecretRef != nil {
		in, out := &in.BindingSecretRef, &out.BindingSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseGatewaySpec.
func (in *ClickHouseGatewaySpec) DeepCopy() *ClickHouseGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(ClickHouseGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseGatewayStatus) DeepCopyInto(out *ClickHouseGatewayStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseGatewayStatus.
func (in *ClickHouseGatewayStatus) DeepCopy() *ClickHouseGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(ClickHouseGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseKeeperSpec) DeepCopyInto(out *ClickHouseKeeperSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Instance != nil {
		in, out := &in.Instance, &out.Instance
		*out = new(shared.InstanceSetSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseKeeperSpec.
func (in *ClickHouseKeeperSpec) DeepCopy() *ClickHouseKeeperSpec {
	if in == nil {
		return nil
	}
	out := new(ClickHouseKeeperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseKeeperStatus) DeepCopyInto(out *ClickHouseKeeperStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseKeeperStatus.
func (in *ClickHouseKeeperStatus) DeepCopy() *ClickHouseKeeperStatus {
	if in == nil {
		return nil
	}
	out := new(ClickHouseKeeperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseSpec) DeepCopyInto(out *ClickHouseSpec) {
	*out = *in
	in.Keeper.DeepCopyInto(&out.Keeper)
	if in.ComputeGroups != nil {
		in, out := &in.ComputeGroups, &out.ComputeGroups
		*out = make([]ClickHouseComputeGroupSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(ClickHouseGatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(ClickHouseBackupSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseSpec.
func (in *ClickHouseSpec) DeepCopy() *ClickHouseSpec {
	if in == nil {
		return nil
	}
	out := new(ClickHouseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseStatus) DeepCopyInto(out *ClickHouseStatus) {
	*out = *in
	if in.Keeper != nil {
		in, out := &in.Keeper, &out.Keeper
		*out = new(ClickHouseKeeperStatus)
		**out = **in
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(ClickHouseGatewayStatus)
		**out = **in
	}
	if in.ComputeGroups != nil {
		in, out := &in.ComputeGroups, &out.ComputeGroups
		*out = make([]ClickHouseComputeGroupStatus, len(*in))
		copy(*out, *in)
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(ClickHouseVersionStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseStatus.
func (in *ClickHouseStatus) DeepCopy() *ClickHouseStatus {
	if in == nil {
		return nil
	}
	out := new(ClickHouseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseVersionStatus) DeepCopyInto(out *ClickHouseVersionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseVersionStatus.
func (in *ClickHouseVersionStatus) DeepCopy() *ClickHouseVersionStatus {
	if in == nil {
		return nil
	}
	out := new(ClickHouseVersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBBackup) DeepCopyInto(out *DBBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBBackup.
func (in *DBBackup) DeepCopy() *DBBackup {
	if in == nil {
		return nil
	}
	out := new(DBBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBBackupArtifactStatus) DeepCopyInto(out *DBBackupArtifactStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.StopTime != nil {
		in, out := &in.StopTime, &out.StopTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBBackupArtifactStatus.
func (in *DBBackupArtifactStatus) DeepCopy() *DBBackupArtifactStatus {
	if in == nil {
		return nil
	}
	out := new(DBBackupArtifactStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBBackupList) DeepCopyInto(out *DBBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBBackupList.
func (in *DBBackupList) DeepCopy() *DBBackupList {
	if in == nil {
		return nil
	}
	out := new(DBBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBBackupSpec) DeepCopyInto(out *DBBackupSpec) {
	*out = *in
	out.InstanceRef = in.InstanceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBBackupSpec.
func (in *DBBackupSpec) DeepCopy() *DBBackupSpec {
	if in == nil {
		return nil
	}
	out := new(DBBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBBackupStatus) DeepCopyInto(out *DBBackupStatus) {
	*out = *in
	if in.Artifact != nil {
		in, out := &in.Artifact, &out.Artifact
		*out = new(DBBackupArtifactStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.PITRWindowStart != nil {
		in, out := &in.PITRWindowStart, &out.PITRWindowStart
		*out = (*in).DeepCopy()
	}
	if in.PITRWindowEnd != nil {
		in, out := &in.PITRWindowEnd, &out.PITRWindowEnd
		*out = (*in).DeepCopy()
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBBackupStatus.
func (in *DBBackupStatus) DeepCopy() *DBBackupStatus {
	if in == nil {
		return nil
	}
	out := new(DBBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBFailover) DeepCopyInto(out *DBFailover) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBFailover.
func (in *DBFailover) DeepCopy() *DBFailover {
	if in == nil {
		return nil
	}
	out := new(DBFailover)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBFailover) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBFailoverList) DeepCopyInto(out *DBFailoverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBFailover, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBFailoverList.
func (in *DBFailoverList) DeepCopy() *DBFailoverList {
	if in == nil {
		return nil
	}
	out := new(DBFailoverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBFailoverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBFailoverSpec) DeepCopyInto(out *DBFailoverSpec) {
	*out = *in
	out.InstanceRef = in.InstanceRef
	if in.Approvers != nil {
		in, out := &in.Approvers, &out.Approvers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBFailoverSpec.
func (in *DBFailoverSpec) DeepCopy() *DBFailoverSpec {
	if in == nil {
		return nil
	}
	out := new(DBFailoverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBFailoverStatus) DeepCopyInto(out *DBFailoverStatus) {
	*out = *in
	if in.Approvers != nil {
		in, out := &in.Approvers, &out.Approvers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]DBFailoverStepStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBFailoverStatus.
func (in *DBFailoverStatus) DeepCopy() *DBFailoverStatus {
	if in == nil {
		return nil
	}
	out := new(DBFailoverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBFailoverStepStatus) DeepCopyInto(out *DBFailoverStepStatus) {
	*out = *in
	in.UpdatedAt.DeepCopyInto(&out.UpdatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBFailoverStepStatus.
func (in *DBFailoverStepStatus) DeepCopy() *DBFailoverStepStatus {
	if in == nil {
		return nil
	}
	out := new(DBFailoverStepStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBRestore) DeepCopyInto(out *DBRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBRestore.
func (in *DBRestore) DeepCopy() *DBRestore {
	if in == nil {
		return nil
	}
	out := new(DBRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBRestoreList) DeepCopyInto(out *DBRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DBRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBRestoreList.
func (in *DBRestoreList) DeepCopy() *DBRestoreList {
	if in == nil {
		return nil
	}
	out := new(DBRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DBRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBRestoreSpec) DeepCopyInto(out *DBRestoreSpec) {
	*out = *in
	out.BackupRef = in.BackupRef
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBRestoreSpec.
func (in *DBRestoreSpec) DeepCopy() *DBRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(DBRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBRestoreStatus) DeepCopyInto(out *DBRestoreStatus) {
	*out = *in
	if in.SourceInstanceRef != nil {
		in, out := &in.SourceInstanceRef, &out.SourceInstanceRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.TargetInstanceRef != nil {
		in, out := &in.TargetInstanceRef, &out.TargetInstanceRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBRestoreStatus.
func (in *DBRestoreStatus) DeepCopy() *DBRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(DBRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBRestoreTarget) DeepCopyInto(out *DBRestoreTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBRestoreTarget.
func (in *DBRestoreTarget) DeepCopy() *DBRestoreTarget {
	if in == nil {
		return nil
	}
	out := new(DBRestoreTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostInfo) DeepCopyInto(out *HostInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostInfo.
func (in *HostInfo) DeepCopy() *HostInfo {
	if in == nil {
		return nil
	}
	out := new(HostInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceDesc) DeepCopyInto(out *InstanceDesc) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.RuntimeClassName != nil {
		in, out := &in.RuntimeClassName, &out.RuntimeClassName
		*out = new(string)
		**out = **in
	}
	if in.PriorityClassName != nil {
		in, out := &in.PriorityClassName, &out.PriorityClassName
		*out = new(string)
		**out = **in
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	out.Size = in.Size.DeepCopy()
	out.LogSize = in.LogSize.DeepCopy()
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceDesc.
func (in *InstanceDesc) DeepCopy() *InstanceDesc {
	if in == nil {
		return nil
	}
	out := new(InstanceDesc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBCluster) DeepCopyInto(out *KDBCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBCluster.
func (in *KDBCluster) DeepCopy() *KDBCluster {
	if in == nil {
		return nil
	}
	out := new(KDBCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBClusterList) DeepCopyInto(out *KDBClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDBCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBClusterList.
func (in *KDBClusterList) DeepCopy() *KDBClusterList {
	if in == nil {
		return nil
	}
	out := new(KDBClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBClusterSpec) DeepCopyInto(out *KDBClusterSpec) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]InstanceDesc, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Leader = in.Leader
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(MySQLSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PostgreSQL != nil {
		in, out := &in.PostgreSQL, &out.PostgreSQL
		*out = new(PostgreSQLSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(KDBProxySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBClusterSpec.
func (in *KDBClusterSpec) DeepCopy() *KDBClusterSpec {
	if in == nil {
		return nil
	}
	out := new(KDBClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBClusterStatus) DeepCopyInto(out *KDBClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(KDBProxyStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBClusterStatus.
func (in *KDBClusterStatus) DeepCopy() *KDBClusterStatus {
	if in == nil {
		return nil
	}
	out := new(KDBClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBInstance) DeepCopyInto(out *KDBInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBInstance.
func (in *KDBInstance) DeepCopy() *KDBInstance {
	if in == nil {
		return nil
	}
	out := new(KDBInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBInstanceList) DeepCopyInto(out *KDBInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDBInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBInstanceList.
func (in *KDBInstanceList) DeepCopy() *KDBInstanceList {
	if in == nil {
		return nil
	}
	out := new(KDBInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBInstanceSpec) DeepCopyInto(out *KDBInstanceSpec) {
	*out = *in
	in.InstanceSet.DeepCopyInto(&out.InstanceSet)
	out.Leader = in.Leader
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(MySQLSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(KDBProxySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PostgreSQL != nil {
		in, out := &in.PostgreSQL, &out.PostgreSQL
		*out = new(PostgreSQLSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ClickHouse != nil {
		in, out := &in.ClickHouse, &out.ClickHouse
		*out = new(ClickHouseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Shutdown != nil {
		in, out := &in.Shutdown, &out.Shutdown
		*out = new(bool)
		**out = **in
	}
	if in.SupplementalGroups != nil {
		in, out := &in.SupplementalGroups, &out.SupplementalGroups
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBInstanceSpec.
func (in *KDBInstanceSpec) DeepCopy() *KDBInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(KDBInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBInstanceStatus) DeepCopyInto(out *KDBInstanceStatus) {
	*out = *in
	in.InstanceSet.DeepCopyInto(&out.InstanceSet)
	if in.PostgreSQL != nil {
		in, out := &in.PostgreSQL, &out.PostgreSQL
		*out = new(PostgreSQLStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ClickHouse != nil {
		in, out := &in.ClickHouse, &out.ClickHouse
		*out = new(ClickHouseStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(KDBProxyStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBInstanceStatus.
func (in *KDBInstanceStatus) DeepCopy() *KDBInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(KDBInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBLogSystem) DeepCopyInto(out *KDBLogSystem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBLogSystem.
func (in *KDBLogSystem) DeepCopy() *KDBLogSystem {
	if in == nil {
		return nil
	}
	out := new(KDBLogSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBLogSystem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBLogSystemList) DeepCopyInto(out *KDBLogSystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDBLogSystem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBLogSystemList.
func (in *KDBLogSystemList) DeepCopy() *KDBLogSystemList {
	if in == nil {
		return nil
	}
	out := new(KDBLogSystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBLogSystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBLogSystemSpec) DeepCopyInto(out *KDBLogSystemSpec) {
	*out = *in
	out.Endpoints = in.Endpoints
	if in.CredentialSecretRef != nil {
		in, out := &in.CredentialSecretRef, &out.CredentialSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	in.Collector.DeepCopyInto(&out.Collector)
	in.Gateway.DeepCopyInto(&out.Gateway)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBLogSystemSpec.
func (in *KDBLogSystemSpec) DeepCopy() *KDBLogSystemSpec {
	if in == nil {
		return nil
	}
	out := new(KDBLogSystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBLogSystemStatus) DeepCopyInto(out *KDBLogSystemStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBLogSystemStatus.
func (in *KDBLogSystemStatus) DeepCopy() *KDBLogSystemStatus {
	if in == nil {
		return nil
	}
	out := new(KDBLogSystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBMonitoringStack) DeepCopyInto(out *KDBMonitoringStack) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBMonitoringStack.
func (in *KDBMonitoringStack) DeepCopy() *KDBMonitoringStack {
	if in == nil {
		return nil
	}
	out := new(KDBMonitoringStack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBMonitoringStack) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBMonitoringStackList) DeepCopyInto(out *KDBMonitoringStackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KDBMonitoringStack, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBMonitoringStackList.
func (in *KDBMonitoringStackList) DeepCopy() *KDBMonitoringStackList {
	if in == nil {
		return nil
	}
	out := new(KDBMonitoringStackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KDBMonitoringStackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBMonitoringStackSpec) DeepCopyInto(out *KDBMonitoringStackSpec) {
	*out = *in
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	in.Alertmanager.DeepCopyInto(&out.Alertmanager)
	in.Grafana.DeepCopyInto(&out.Grafana)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBMonitoringStackSpec.
func (in *KDBMonitoringStackSpec) DeepCopy() *KDBMonitoringStackSpec {
	if in == nil {
		return nil
	}
	out := new(KDBMonitoringStackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBMonitoringStackStatus) DeepCopyInto(out *KDBMonitoringStackStatus) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]MonitoringStackComponentStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBMonitoringStackStatus.
func (in *KDBMonitoringStackStatus) DeepCopy() *KDBMonitoringStackStatus {
	if in == nil {
		return nil
	}
	out := new(KDBMonitoringStackStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyBackendPolicySpec) DeepCopyInto(out *KDBProxyBackendPolicySpec) {
	*out = *in
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(KDBProxyHealthCheckSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyBackendPolicySpec.
func (in *KDBProxyBackendPolicySpec) DeepCopy() *KDBProxyBackendPolicySpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyBackendPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyBackendStatus) DeepCopyInto(out *KDBProxyBackendStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyBackendStatus.
func (in *KDBProxyBackendStatus) DeepCopy() *KDBProxyBackendStatus {
	if in == nil {
		return nil
	}
	out := new(KDBProxyBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyConfigMapRef) DeepCopyInto(out *KDBProxyConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyConfigMapRef.
func (in *KDBProxyConfigMapRef) DeepCopy() *KDBProxyConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(KDBProxyConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyConfigSpec) DeepCopyInto(out *KDBProxyConfigSpec) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(KDBProxyConfigMapRef)
		**out = **in
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(KDBProxyInlineConfigSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyConfigSpec.
func (in *KDBProxyConfigSpec) DeepCopy() *KDBProxyConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyHealthCheckSpec) DeepCopyInto(out *KDBProxyHealthCheckSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyHealthCheckSpec.
func (in *KDBProxyHealthCheckSpec) DeepCopy() *KDBProxyHealthCheckSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyHealthCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyHostgroupsStatus) DeepCopyInto(out *KDBProxyHostgroupsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyHostgroupsStatus.
func (in *KDBProxyHostgroupsStatus) DeepCopy() *KDBProxyHostgroupsStatus {
	if in == nil {
		return nil
	}
	out := new(KDBProxyHostgroupsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyInlineConfigSpec) DeepCopyInto(out *KDBProxyInlineConfigSpec) {
	*out = *in
	if in.Traffic != nil {
		in, out := &in.Traffic, &out.Traffic
		*out = new(KDBProxyTrafficPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = new(KDBProxyBackendPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]KDBProxyUserSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyInlineConfigSpec.
func (in *KDBProxyInlineConfigSpec) DeepCopy() *KDBProxyInlineConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyInlineConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyLoadBalanceSpec) DeepCopyInto(out *KDBProxyLoadBalanceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyLoadBalanceSpec.
func (in *KDBProxyLoadBalanceSpec) DeepCopy() *KDBProxyLoadBalanceSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyLoadBalanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyReadWriteSplitSpec) DeepCopyInto(out *KDBProxyReadWriteSplitSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyReadWriteSplitSpec.
func (in *KDBProxyReadWriteSplitSpec) DeepCopy() *KDBProxyReadWriteSplitSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyReadWriteSplitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyResourceSpec) DeepCopyInto(out *KDBProxyResourceSpec) {
	*out = *in
	in.ProxySQL.DeepCopyInto(&out.ProxySQL)
	in.Mgr.DeepCopyInto(&out.Mgr)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyResourceSpec.
func (in *KDBProxyResourceSpec) DeepCopy() *KDBProxyResourceSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyServiceSpec) DeepCopyInto(out *KDBProxyServiceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyServiceSpec.
func (in *KDBProxyServiceSpec) DeepCopy() *KDBProxyServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxySpec) DeepCopyInto(out *KDBProxySpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(KDBProxyConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(KDBProxyServiceSpec)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(KDBProxyResourceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxySpec.
func (in *KDBProxySpec) DeepCopy() *KDBProxySpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyStatus) DeepCopyInto(out *KDBProxyStatus) {
	*out = *in
	if in.Hostgroups != nil {
		in, out := &in.Hostgroups, &out.Hostgroups
		*out = new(KDBProxyHostgroupsStatus)
		**out = **in
	}
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]KDBProxyBackendStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyStatus.
func (in *KDBProxyStatus) DeepCopy() *KDBProxyStatus {
	if in == nil {
		return nil
	}
	out := new(KDBProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyTrafficPolicySpec) DeepCopyInto(out *KDBProxyTrafficPolicySpec) {
	*out = *in
	if in.ReadWriteSplit != nil {
		in, out := &in.ReadWriteSplit, &out.ReadWriteSplit
		*out = new(KDBProxyReadWriteSplitSpec)
		**out = **in
	}
	if in.LoadBalance != nil {
		in, out := &in.LoadBalance, &out.LoadBalance
		*out = new(KDBProxyLoadBalanceSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyTrafficPolicySpec.
func (in *KDBProxyTrafficPolicySpec) DeepCopy() *KDBProxyTrafficPolicySpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyTrafficPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KDBProxyUserSpec) DeepCopyInto(out *KDBProxyUserSpec) {
	*out = *in
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KDBProxyUserSpec.
func (in *KDBProxyUserSpec) DeepCopy() *KDBProxyUserSpec {
	if in == nil {
		return nil
	}
	out := new(KDBProxyUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogSystemCollectorSpec) DeepCopyInto(out *LogSystemCollectorSpec) {
	*out = *in
	if in.ExtraLogDirs != nil {
		in, out := &in.ExtraLogDirs, &out.ExtraLogDirs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigPatch != nil {
		in, out := &in.ConfigPatch, &out.ConfigPatch
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogSystemCollectorSpec.
func (in *LogSystemCollectorSpec) DeepCopy() *LogSystemCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(LogSystemCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogSystemEndpointSpec) DeepCopyInto(out *LogSystemEndpointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogSystemEndpointSpec.
func (in *LogSystemEndpointSpec) DeepCopy() *LogSystemEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(LogSystemEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogSystemGatewaySpec) DeepCopyInto(out *LogSystemGatewaySpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogSystemGatewaySpec.
func (in *LogSystemGatewaySpec) DeepCopy() *LogSystemGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(LogSystemGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringStackAlertmanagerSpec) DeepCopyInto(out *MonitoringStackAlertmanagerSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringStackAlertmanagerSpec.
func (in *MonitoringStackAlertmanagerSpec) DeepCopy() *MonitoringStackAlertmanagerSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringStackAlertmanagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringStackComponentStatus) DeepCopyInto(out *MonitoringStackComponentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringStackComponentStatus.
func (in *MonitoringStackComponentStatus) DeepCopy() *MonitoringStackComponentStatus {
	if in == nil {
		return nil
	}
	out := new(MonitoringStackComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringStackGrafanaSpec) DeepCopyInto(out *MonitoringStackGrafanaSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringStackGrafanaSpec.
func (in *MonitoringStackGrafanaSpec) DeepCopy() *MonitoringStackGrafanaSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringStackGrafanaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringStackPrometheusSpec) DeepCopyInto(out *MonitoringStackPrometheusSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringStackPrometheusSpec.
func (in *MonitoringStackPrometheusSpec) DeepCopy() *MonitoringStackPrometheusSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringStackPrometheusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLExporterSpec) DeepCopyInto(out *MySQLExporterSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLExporterSpec.
func (in *MySQLExporterSpec) DeepCopy() *MySQLExporterSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLMGRSpec) DeepCopyInto(out *MySQLMGRSpec) {
	*out = *in
	if in.BootstrapOrdinal != nil {
		in, out := &in.BootstrapOrdinal, &out.BootstrapOrdinal
		*out = new(int32)
		**out = **in
	}
	if in.GroupPort != nil {
		in, out := &in.GroupPort, &out.GroupPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLMGRSpec.
func (in *MySQLMGRSpec) DeepCopy() *MySQLMGRSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLMGRSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLSpec) DeepCopyInto(out *MySQLSpec) {
	*out = *in
	if in.MGR != nil {
		in, out := &in.MGR, &out.MGR
		*out = new(MySQLMGRSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Exporter != nil {
		in, out := &in.Exporter, &out.Exporter
		*out = new(MySQLExporterSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLSpec.
func (in *MySQLSpec) DeepCopy() *MySQLSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLBackupSpec) DeepCopyInto(out *PostgreSQLBackupSpec) {
	*out = *in
	if in.PGBackRest != nil {
		in, out := &in.PGBackRest, &out.PGBackRest
		*out = new(PostgreSQLPGBackRestSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLBackupSpec.
func (in *PostgreSQLBackupSpec) DeepCopy() *PostgreSQLBackupSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLBootstrapParametersStatus) DeepCopyInto(out *PostgreSQLBootstrapParametersStatus) {
	*out = *in
	in.AppliedAt.DeepCopyInto(&out.AppliedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLBootstrapParametersStatus.
func (in *PostgreSQLBootstrapParametersStatus) DeepCopy() *PostgreSQLBootstrapParametersStatus {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLBootstrapParametersStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLCustomExtensionImage) DeepCopyInto(out *PostgreSQLCustomExtensionImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLCustomExtensionImage.
func (in *PostgreSQLCustomExtensionImage) DeepCopy() *PostgreSQLCustomExtensionImage {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLCustomExtensionImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLDRDrillStatus) DeepCopyInto(out *PostgreSQLDRDrillStatus) {
	*out = *in
	if in.Approvers != nil {
		in, out := &in.Approvers, &out.Approvers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLDRDrillStatus.
func (in *PostgreSQLDRDrillStatus) DeepCopy() *PostgreSQLDRDrillStatus {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLDRDrillStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLDREtcd3Spec) DeepCopyInto(out *PostgreSQLDREtcd3Spec) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLDREtcd3Spec.
func (in *PostgreSQLDREtcd3Spec) DeepCopy() *PostgreSQLDREtcd3Spec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLDREtcd3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLDRHeartbeat) DeepCopyInto(out *PostgreSQLDRHeartbeat) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLDRHeartbeat.
func (in *PostgreSQLDRHeartbeat) DeepCopy() *PostgreSQLDRHeartbeat {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLDRHeartbeat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLDRSpec) DeepCopyInto(out *PostgreSQLDRSpec) {
	*out = *in
	in.Etcd3.DeepCopyInto(&out.Etcd3)
	out.WALSource = in.WALSource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLDRSpec.
func (in *PostgreSQLDRSpec) DeepCopy() *PostgreSQLDRSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLDRSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLDRStatus) DeepCopyInto(out *PostgreSQLDRStatus) {
	*out = *in
	if in.LastPromotedAt != nil {
		in, out := &in.LastPromotedAt, &out.LastPromotedAt
		*out = (*in).DeepCopy()
	}
	if in.LastFencedAt != nil {
		in, out := &in.LastFencedAt, &out.LastFencedAt
		*out = (*in).DeepCopy()
	}
	if in.LastDrill != nil {
		in, out := &in.LastDrill, &out.LastDrill
		*out = new(PostgreSQLDRDrillStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterHeartbeats != nil {
		in, out := &in.ClusterHeartbeats, &out.ClusterHeartbeats
		*out = make(map[string]PostgreSQLDRHeartbeat, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLDRStatus.
func (in *PostgreSQLDRStatus) DeepCopy() *PostgreSQLDRStatus {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLDRStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLDRWALSource) DeepCopyInto(out *PostgreSQLDRWALSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLDRWALSource.
func (in *PostgreSQLDRWALSource) DeepCopy() *PostgreSQLDRWALSource {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLDRWALSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLExporterSpec) DeepCopyInto(out *PostgreSQLExporterSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLExporterSpec.
func (in *PostgreSQLExporterSpec) DeepCopy() *PostgreSQLExporterSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLExtensionSpec) DeepCopyInto(out *PostgreSQLExtensionSpec) {
	*out = *in
	if in.CustomImage != nil {
		in, out := &in.CustomImage, &out.CustomImage
		*out = new(PostgreSQLCustomExtensionImage)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLExtensionSpec.
func (in *PostgreSQLExtensionSpec) DeepCopy() *PostgreSQLExtensionSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLExtensionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLHASpec) DeepCopyInto(out *PostgreSQLHASpec) {
	*out = *in
	if in.MaximumLagOnFailoverBytes != nil {
		in, out := &in.MaximumLagOnFailoverBytes, &out.MaximumLagOnFailoverBytes
		*out = new(int64)
		**out = **in
	}
	if in.MaximumLagOnSyncNodeBytes != nil {
		in, out := &in.MaximumLagOnSyncNodeBytes, &out.MaximumLagOnSyncNodeBytes
		*out = new(int64)
		**out = **in
	}
	if in.SynchronousNodeCount != nil {
		in, out := &in.SynchronousNodeCount, &out.SynchronousNodeCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLHASpec.
func (in *PostgreSQLHASpec) DeepCopy() *PostgreSQLHASpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLHASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLLifecycleSpec) DeepCopyInto(out *PostgreSQLLifecycleSpec) {
	*out = *in
	if in.Upgrade != nil {
		in, out := &in.Upgrade, &out.Upgrade
		*out = new(PostgreSQLUpgradeSpec)
		**out = **in
	}
	if in.Rebuild != nil {
		in, out := &in.Rebuild, &out.Rebuild
		*out = new(PostgreSQLRebuildSpec)
		**out = **in
	}
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make([]PostgreSQLExtensionSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLLifecycleSpec.
func (in *PostgreSQLLifecycleSpec) DeepCopy() *PostgreSQLLifecycleSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLLifecycleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLLifecycleStatus) DeepCopyInto(out *PostgreSQLLifecycleStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLLifecycleStatus.
func (in *PostgreSQLLifecycleStatus) DeepCopy() *PostgreSQLLifecycleStatus {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLLifecycleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLMemberStatus) DeepCopyInto(out *PostgreSQLMemberStatus) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLMemberStatus.
func (in *PostgreSQLMemberStatus) DeepCopy() *PostgreSQLMemberStatus {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLMemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLPGBackRestSpec) DeepCopyInto(out *PostgreSQLPGBackRestSpec) {
	*out = *in
	if in.RepoSecretRef != nil {
		in, out := &in.RepoSecretRef, &out.RepoSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.RetentionFull != nil {
		in, out := &in.RetentionFull, &out.RetentionFull
		*out = new(int32)
		**out = **in
	}
	if in.RetentionDays != nil {
		in, out := &in.RetentionDays, &out.RetentionDays
		*out = new(int32)
		**out = **in
	}
	if in.S3TLSVerify != nil {
		in, out := &in.S3TLSVerify, &out.S3TLSVerify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLPGBackRestSpec.
func (in *PostgreSQLPGBackRestSpec) DeepCopy() *PostgreSQLPGBackRestSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLPGBackRestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLPGBackRestStatus) DeepCopyInto(out *PostgreSQLPGBackRestStatus) {
	*out = *in
	if in.LastSuccessfulBackupTime != nil {
		in, out := &in.LastSuccessfulBackupTime, &out.LastSuccessfulBackupTime
		*out = (*in).DeepCopy()
	}
	if in.LastRestoreValidationTime != nil {
		in, out := &in.LastRestoreValidationTime, &out.LastRestoreValidationTime
		*out = (*in).DeepCopy()
	}
	if in.PITRWindowStart != nil {
		in, out := &in.PITRWindowStart, &out.PITRWindowStart
		*out = (*in).DeepCopy()
	}
	if in.PITRWindowEnd != nil {
		in, out := &in.PITRWindowEnd, &out.PITRWindowEnd
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLPGBackRestStatus.
func (in *PostgreSQLPGBackRestStatus) DeepCopy() *PostgreSQLPGBackRestStatus {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLPGBackRestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLPatroniSpec) DeepCopyInto(out *PostgreSQLPatroniSpec) {
	*out = *in
	if in.LeaderLeaseDurationSeconds != nil {
		in, out := &in.LeaderLeaseDurationSeconds, &out.LeaderLeaseDurationSeconds
		*out = new(int32)
		**out = **in
	}
	if in.SyncPeriodSeconds != nil {
		in, out := &in.SyncPeriodSeconds, &out.SyncPeriodSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLPatroniSpec.
func (in *PostgreSQLPatroniSpec) DeepCopy() *PostgreSQLPatroniSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLPatroniSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLPgBouncerSpec) DeepCopyInto(out *PostgreSQLPgBouncerSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLPgBouncerSpec.
func (in *PostgreSQLPgBouncerSpec) DeepCopy() *PostgreSQLPgBouncerSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLPgBouncerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLPgBouncerStatus) DeepCopyInto(out *PostgreSQLPgBouncerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLPgBouncerStatus.
func (in *PostgreSQLPgBouncerStatus) DeepCopy() *PostgreSQLPgBouncerStatus {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLPgBouncerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLRebuildSpec) DeepCopyInto(out *PostgreSQLRebuildSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLRebuildSpec.
func (in *PostgreSQLRebuildSpec) DeepCopy() *PostgreSQLRebuildSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLRebuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLRestoreBootstrapSpec) DeepCopyInto(out *PostgreSQLRestoreBootstrapSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLRestoreBootstrapSpec.
func (in *PostgreSQLRestoreBootstrapSpec) DeepCopy() *PostgreSQLRestoreBootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLRestoreBootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLServiceStatus) DeepCopyInto(out *PostgreSQLServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLServiceStatus.
func (in *PostgreSQLServiceStatus) DeepCopy() *PostgreSQLServiceStatus {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLSpec) DeepCopyInto(out *PostgreSQLSpec) {
	*out = *in
	if in.HA != nil {
		in, out := &in.HA, &out.HA
		*out = new(PostgreSQLHASpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PgBouncer != nil {
		in, out := &in.PgBouncer, &out.PgBouncer
		*out = new(PostgreSQLPgBouncerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Patroni != nil {
		in, out := &in.Patroni, &out.Patroni
		*out = new(PostgreSQLPatroniSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Backups != nil {
		in, out := &in.Backups, &out.Backups
		*out = new(PostgreSQLBackupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialSecretRef != nil {
		in, out := &in.CredentialSecretRef, &out.CredentialSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Exporter != nil {
		in, out := &in.Exporter, &out.Exporter
		*out = new(PostgreSQLExporterSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HBA != nil {
		in, out := &in.HBA, &out.HBA
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(PostgreSQLRestoreBootstrapSpec)
		**out = **in
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(PostgreSQLLifecycleSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DR != nil {
		in, out := &in.DR, &out.DR
		*out = new(PostgreSQLDRSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLSpec.
func (in *PostgreSQLSpec) DeepCopy() *PostgreSQLSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLStatus) DeepCopyInto(out *PostgreSQLStatus) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]PostgreSQLMemberStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BootstrapParameters != nil {
		in, out := &in.BootstrapParameters, &out.BootstrapParameters
		*out = new(PostgreSQLBootstrapParametersStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]HostInfo, len(*in))
		copy(*out, *in)
	}
	if in.PGBackRest != nil {
		in, out := &in.PGBackRest, &out.PGBackRest
		*out = new(PostgreSQLPGBackRestStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(PostgreSQLLifecycleStatus)
		(*in).DeepCopyInto(*out)
	}
	out.Services = in.Services
	if in.PgBouncer != nil {
		in, out := &in.PgBouncer, &out.PgBouncer
		*out = new(PostgreSQLPgBouncerStatus)
		**out = **in
	}
	if in.DR != nil {
		in, out := &in.DR, &out.DR
		*out = new(PostgreSQLDRStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLStatus.
func (in *PostgreSQLStatus) DeepCopy() *PostgreSQLStatus {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLUpgradeSpec) DeepCopyInto(out *PostgreSQLUpgradeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLUpgradeSpec.
func (in *PostgreSQLUpgradeSpec) DeepCopy() *PostgreSQLUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}
