apiVersion: kdb.com/v1
kind: KDBInstance
metadata:
  name: demo-postgresql
  namespace: kdb
spec:
  engine: postgresql
  engineVersion: "17"
  engineFullVersion: "17"
  deployArch: Single
  port: 5432
  instance:
    replicas: 1
    mainContainer:
      image: kdbdeveloper/postgresql17:v0.0.1
    sidecarContainer:
      image: kdbdeveloper/postgresql-sidecar:v0.0.1
      command: [kdb-ha]
      args: [/etc/patroni/patroni.yaml]
    dataVolumeClaimSpec:
      storageClass: standard
      size: 10Gi
    logVolumeClaimSpec:
      storageClass: standard
      size: 5Gi
  postgresql:
    patroni:
      dcs: kubernetes
      leaderLeaseDurationSeconds: 30
      syncPeriodSeconds: 10
    parameters:
      max_connections: "200"
    # exporter:
    #   enabled: true
    #   image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
    #   env:
    #     - name: DATA_SOURCE_URI
    #       value: localhost:5432/postgres?sslmode=disable
