# kind create cluster --name my-multi-node-cluster --config kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
  - role: worker


# load docker images:  kind load docker-image kdbdeveloper/operator:v0.0.1
#
#