package naming

import "k8s.io/apimachinery/pkg/labels"

const (
	YamlGeneratedWarning = "" +
		"# Generated by kdb-operator. DO NOT EDIT.\n" +
		"# Your changes will not be saved.\n"
)

const (
	SidecarConfigKey  = "sidecar"
	DatabaseConfigKey = "database"
)

// Merge takes sets of labels and merges them. The last set
// provided will win in case of conflicts.
func Merge(sets ...map[string]string) labels.Set {
	merged := labels.Set{}
	for _, set := range sets {
		if len(set) > 0 {
			merged = labels.Merge(merged, set)
		}
	}
	return merged
}
