package naming

import "k8s.io/apimachinery/pkg/labels"

const (
	YamlGeneratedWarning = "" +
		"# Generated by kdb-operator. DO NOT EDIT.\n" +
		"# Your changes will not be saved.\n"
)

const (
	SidecarConfigKey        = "sidecar"
	DatabaseConfigKey       = "database"
	PatroniConfigKey        = "patroni.yaml"
	SidecarConfigMapFileKey = "config.yaml"
	MySQLConfigMapFileKey   = "my.cnf"
)

const (
	ParameterReportHostSecretKey    = "report_host"
	ParameterReportTokenSecretKey   = "report_token"
	ParameterReportCatalogSecretKey = "parameter_catalog.json"

	ParameterReportHostPath    = ConfigMountPath + "/" + ParameterReportHostSecretKey
	ParameterReportTokenPath   = ConfigMountPath + "/" + ParameterReportTokenSecretKey
	ParameterReportCatalogPath = ConfigMountPath + "/" + ParameterReportCatalogSecretKey
)

const (
	// DataMountPath is where to mount the main data volume.
	DataMountPath = "/kdbdata"

	// LogMountPath is where to mount the optional WAL volume.
	LogMountPath = "/kdblog"

	// DownwardAPIPath is where to mount the downwardAPI volume.
	DownwardAPIPath = "/etc/containerinfo"

	// ConfigMountPath is where to mount the config volume.
	ConfigMountPath = "/etc/config"

	// PostgreSQLDataMountPath is where PostgreSQL data volumes are mounted.
	PostgreSQLDataMountPath = "/pgdata"

	// PostgreSQLWALMountPath is where PostgreSQL WAL volumes are mounted.
	PostgreSQLWALMountPath = "/pgwal"

	// PatroniConfigMountPath is where Patroni configuration is mounted.
	PatroniConfigMountPath = "/etc/patroni"

	// PostgreSQLSocketDirectory is where PostgreSQL UNIX sockets are created.
	PostgreSQLSocketDirectory = "/tmp/postgres"
)

// Merge takes sets of labels and merges them. The last set
// provided will win in case of conflicts.
func Merge(sets ...map[string]string) labels.Set {
	merged := labels.Set{}
	for _, set := range sets {
		if len(set) > 0 {
			merged = labels.Merge(merged, set)
		}
	}
	return merged
}
