apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdb-operator
  namespace: kdb
  labels:
    app: kdb-operator
spec:
  replicas: 1
  revisionHistoryLimit: 20     #保留历史版本，默认是10
  progressDeadlineSeconds: 180 #部署超时时间(s)，默认是600
  strategy: #策略
    type: RollingUpdate  #滚动更新策略(就是杀死一部分，就启动一部分，在更新过程中，存在两个版本pod,type=Recreate：在创建出新的pod之前会先杀掉所有已存在的pod)
  selector:   #选择器，通过它指定该控制器管理哪些pod
    matchLabels:
      app: kdb-operator
  template:     #模板，当副本数量不足时，会根据下面的模板创建pod副本
    metadata:
      labels:
        app: kdb-operator
    spec:
      serviceAccount: kdb
      containers:
        - name: kdb-operator
          image: kdbdeveloper/operator:v0.0.3
          imagePullPolicy: IfNotPresent
          env:
            - name: K8SNamespace
              value: kdb
          command:
            - /kdb/bin/manager
          args:
            - operator
          ports:
            - containerPort: 8081
#          resources:
#            limits:
#              cpu: "0.5"
#              memory: "128Mi"
#            requests:
#              cpu: "0.5"
#              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 5

