---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kdb-role
  namespace: kdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kdb-role
subjects:
  - kind: ServiceAccount
    name: kdb
    namespace: kdb